# Generated by Django 3.1.5 on 2021-02-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_vcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcard',
            name='city',
            field=models.TextField(blank=True),
        ),
    ]
