# Generated by Django 3.1.5 on 2021-02-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_vcard_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vcard',
        ),
    ]
